version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ticketflow-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=suasenha123  <-- AQUI ESTÃ A SENHA
      - POSTGRES_DB=ticketflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: